// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bd_test/internals/server/ent/accesskeys"
	"bd_test/internals/server/ent/category"
	"bd_test/internals/server/ent/predicate"
	"bd_test/internals/server/ent/product"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessKeysUpdate is the builder for updating AccessKeys entities.
type AccessKeysUpdate struct {
	config
	hooks    []Hook
	mutation *AccessKeysMutation
}

// Where appends a list predicates to the AccessKeysUpdate builder.
func (aku *AccessKeysUpdate) Where(ps ...predicate.AccessKeys) *AccessKeysUpdate {
	aku.mutation.Where(ps...)
	return aku
}

// SetKey sets the "key" field.
func (aku *AccessKeysUpdate) SetKey(s string) *AccessKeysUpdate {
	aku.mutation.SetKey(s)
	return aku
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (aku *AccessKeysUpdate) SetNillableKey(s *string) *AccessKeysUpdate {
	if s != nil {
		aku.SetKey(*s)
	}
	return aku
}

// SetUser sets the "user" field.
func (aku *AccessKeysUpdate) SetUser(s string) *AccessKeysUpdate {
	aku.mutation.SetUser(s)
	return aku
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (aku *AccessKeysUpdate) SetNillableUser(s *string) *AccessKeysUpdate {
	if s != nil {
		aku.SetUser(*s)
	}
	return aku
}

// AddProductIDs adds the "products" edge to the Product entity by IDs.
func (aku *AccessKeysUpdate) AddProductIDs(ids ...int) *AccessKeysUpdate {
	aku.mutation.AddProductIDs(ids...)
	return aku
}

// AddProducts adds the "products" edges to the Product entity.
func (aku *AccessKeysUpdate) AddProducts(p ...*Product) *AccessKeysUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return aku.AddProductIDs(ids...)
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (aku *AccessKeysUpdate) AddCategoryIDs(ids ...int) *AccessKeysUpdate {
	aku.mutation.AddCategoryIDs(ids...)
	return aku
}

// AddCategories adds the "categories" edges to the Category entity.
func (aku *AccessKeysUpdate) AddCategories(c ...*Category) *AccessKeysUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return aku.AddCategoryIDs(ids...)
}

// Mutation returns the AccessKeysMutation object of the builder.
func (aku *AccessKeysUpdate) Mutation() *AccessKeysMutation {
	return aku.mutation
}

// ClearProducts clears all "products" edges to the Product entity.
func (aku *AccessKeysUpdate) ClearProducts() *AccessKeysUpdate {
	aku.mutation.ClearProducts()
	return aku
}

// RemoveProductIDs removes the "products" edge to Product entities by IDs.
func (aku *AccessKeysUpdate) RemoveProductIDs(ids ...int) *AccessKeysUpdate {
	aku.mutation.RemoveProductIDs(ids...)
	return aku
}

// RemoveProducts removes "products" edges to Product entities.
func (aku *AccessKeysUpdate) RemoveProducts(p ...*Product) *AccessKeysUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return aku.RemoveProductIDs(ids...)
}

// ClearCategories clears all "categories" edges to the Category entity.
func (aku *AccessKeysUpdate) ClearCategories() *AccessKeysUpdate {
	aku.mutation.ClearCategories()
	return aku
}

// RemoveCategoryIDs removes the "categories" edge to Category entities by IDs.
func (aku *AccessKeysUpdate) RemoveCategoryIDs(ids ...int) *AccessKeysUpdate {
	aku.mutation.RemoveCategoryIDs(ids...)
	return aku
}

// RemoveCategories removes "categories" edges to Category entities.
func (aku *AccessKeysUpdate) RemoveCategories(c ...*Category) *AccessKeysUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return aku.RemoveCategoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aku *AccessKeysUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, aku.sqlSave, aku.mutation, aku.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aku *AccessKeysUpdate) SaveX(ctx context.Context) int {
	affected, err := aku.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aku *AccessKeysUpdate) Exec(ctx context.Context) error {
	_, err := aku.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aku *AccessKeysUpdate) ExecX(ctx context.Context) {
	if err := aku.Exec(ctx); err != nil {
		panic(err)
	}
}

func (aku *AccessKeysUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(accesskeys.Table, accesskeys.Columns, sqlgraph.NewFieldSpec(accesskeys.FieldID, field.TypeInt))
	if ps := aku.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aku.mutation.Key(); ok {
		_spec.SetField(accesskeys.FieldKey, field.TypeString, value)
	}
	if value, ok := aku.mutation.User(); ok {
		_spec.SetField(accesskeys.FieldUser, field.TypeString, value)
	}
	if aku.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesskeys.ProductsTable,
			Columns: []string{accesskeys.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aku.mutation.RemovedProductsIDs(); len(nodes) > 0 && !aku.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesskeys.ProductsTable,
			Columns: []string{accesskeys.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aku.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesskeys.ProductsTable,
			Columns: []string{accesskeys.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if aku.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesskeys.CategoriesTable,
			Columns: []string{accesskeys.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aku.mutation.RemovedCategoriesIDs(); len(nodes) > 0 && !aku.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesskeys.CategoriesTable,
			Columns: []string{accesskeys.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aku.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesskeys.CategoriesTable,
			Columns: []string{accesskeys.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aku.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accesskeys.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	aku.mutation.done = true
	return n, nil
}

// AccessKeysUpdateOne is the builder for updating a single AccessKeys entity.
type AccessKeysUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccessKeysMutation
}

// SetKey sets the "key" field.
func (akuo *AccessKeysUpdateOne) SetKey(s string) *AccessKeysUpdateOne {
	akuo.mutation.SetKey(s)
	return akuo
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (akuo *AccessKeysUpdateOne) SetNillableKey(s *string) *AccessKeysUpdateOne {
	if s != nil {
		akuo.SetKey(*s)
	}
	return akuo
}

// SetUser sets the "user" field.
func (akuo *AccessKeysUpdateOne) SetUser(s string) *AccessKeysUpdateOne {
	akuo.mutation.SetUser(s)
	return akuo
}

// SetNillableUser sets the "user" field if the given value is not nil.
func (akuo *AccessKeysUpdateOne) SetNillableUser(s *string) *AccessKeysUpdateOne {
	if s != nil {
		akuo.SetUser(*s)
	}
	return akuo
}

// AddProductIDs adds the "products" edge to the Product entity by IDs.
func (akuo *AccessKeysUpdateOne) AddProductIDs(ids ...int) *AccessKeysUpdateOne {
	akuo.mutation.AddProductIDs(ids...)
	return akuo
}

// AddProducts adds the "products" edges to the Product entity.
func (akuo *AccessKeysUpdateOne) AddProducts(p ...*Product) *AccessKeysUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return akuo.AddProductIDs(ids...)
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (akuo *AccessKeysUpdateOne) AddCategoryIDs(ids ...int) *AccessKeysUpdateOne {
	akuo.mutation.AddCategoryIDs(ids...)
	return akuo
}

// AddCategories adds the "categories" edges to the Category entity.
func (akuo *AccessKeysUpdateOne) AddCategories(c ...*Category) *AccessKeysUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return akuo.AddCategoryIDs(ids...)
}

// Mutation returns the AccessKeysMutation object of the builder.
func (akuo *AccessKeysUpdateOne) Mutation() *AccessKeysMutation {
	return akuo.mutation
}

// ClearProducts clears all "products" edges to the Product entity.
func (akuo *AccessKeysUpdateOne) ClearProducts() *AccessKeysUpdateOne {
	akuo.mutation.ClearProducts()
	return akuo
}

// RemoveProductIDs removes the "products" edge to Product entities by IDs.
func (akuo *AccessKeysUpdateOne) RemoveProductIDs(ids ...int) *AccessKeysUpdateOne {
	akuo.mutation.RemoveProductIDs(ids...)
	return akuo
}

// RemoveProducts removes "products" edges to Product entities.
func (akuo *AccessKeysUpdateOne) RemoveProducts(p ...*Product) *AccessKeysUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return akuo.RemoveProductIDs(ids...)
}

// ClearCategories clears all "categories" edges to the Category entity.
func (akuo *AccessKeysUpdateOne) ClearCategories() *AccessKeysUpdateOne {
	akuo.mutation.ClearCategories()
	return akuo
}

// RemoveCategoryIDs removes the "categories" edge to Category entities by IDs.
func (akuo *AccessKeysUpdateOne) RemoveCategoryIDs(ids ...int) *AccessKeysUpdateOne {
	akuo.mutation.RemoveCategoryIDs(ids...)
	return akuo
}

// RemoveCategories removes "categories" edges to Category entities.
func (akuo *AccessKeysUpdateOne) RemoveCategories(c ...*Category) *AccessKeysUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return akuo.RemoveCategoryIDs(ids...)
}

// Where appends a list predicates to the AccessKeysUpdate builder.
func (akuo *AccessKeysUpdateOne) Where(ps ...predicate.AccessKeys) *AccessKeysUpdateOne {
	akuo.mutation.Where(ps...)
	return akuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (akuo *AccessKeysUpdateOne) Select(field string, fields ...string) *AccessKeysUpdateOne {
	akuo.fields = append([]string{field}, fields...)
	return akuo
}

// Save executes the query and returns the updated AccessKeys entity.
func (akuo *AccessKeysUpdateOne) Save(ctx context.Context) (*AccessKeys, error) {
	return withHooks(ctx, akuo.sqlSave, akuo.mutation, akuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (akuo *AccessKeysUpdateOne) SaveX(ctx context.Context) *AccessKeys {
	node, err := akuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (akuo *AccessKeysUpdateOne) Exec(ctx context.Context) error {
	_, err := akuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (akuo *AccessKeysUpdateOne) ExecX(ctx context.Context) {
	if err := akuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (akuo *AccessKeysUpdateOne) sqlSave(ctx context.Context) (_node *AccessKeys, err error) {
	_spec := sqlgraph.NewUpdateSpec(accesskeys.Table, accesskeys.Columns, sqlgraph.NewFieldSpec(accesskeys.FieldID, field.TypeInt))
	id, ok := akuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccessKeys.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := akuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accesskeys.FieldID)
		for _, f := range fields {
			if !accesskeys.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accesskeys.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := akuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := akuo.mutation.Key(); ok {
		_spec.SetField(accesskeys.FieldKey, field.TypeString, value)
	}
	if value, ok := akuo.mutation.User(); ok {
		_spec.SetField(accesskeys.FieldUser, field.TypeString, value)
	}
	if akuo.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesskeys.ProductsTable,
			Columns: []string{accesskeys.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := akuo.mutation.RemovedProductsIDs(); len(nodes) > 0 && !akuo.mutation.ProductsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesskeys.ProductsTable,
			Columns: []string{accesskeys.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := akuo.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesskeys.ProductsTable,
			Columns: []string{accesskeys.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if akuo.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesskeys.CategoriesTable,
			Columns: []string{accesskeys.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := akuo.mutation.RemovedCategoriesIDs(); len(nodes) > 0 && !akuo.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesskeys.CategoriesTable,
			Columns: []string{accesskeys.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := akuo.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesskeys.CategoriesTable,
			Columns: []string{accesskeys.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccessKeys{config: akuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, akuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accesskeys.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	akuo.mutation.done = true
	return _node, nil
}
