// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bd_test/internals/server/ent/accesskeys"
	"bd_test/internals/server/ent/category"
	"bd_test/internals/server/ent/product"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessKeysCreate is the builder for creating a AccessKeys entity.
type AccessKeysCreate struct {
	config
	mutation *AccessKeysMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (akc *AccessKeysCreate) SetKey(s string) *AccessKeysCreate {
	akc.mutation.SetKey(s)
	return akc
}

// SetUser sets the "user" field.
func (akc *AccessKeysCreate) SetUser(s string) *AccessKeysCreate {
	akc.mutation.SetUser(s)
	return akc
}

// AddProductIDs adds the "products" edge to the Product entity by IDs.
func (akc *AccessKeysCreate) AddProductIDs(ids ...int) *AccessKeysCreate {
	akc.mutation.AddProductIDs(ids...)
	return akc
}

// AddProducts adds the "products" edges to the Product entity.
func (akc *AccessKeysCreate) AddProducts(p ...*Product) *AccessKeysCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return akc.AddProductIDs(ids...)
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (akc *AccessKeysCreate) AddCategoryIDs(ids ...int) *AccessKeysCreate {
	akc.mutation.AddCategoryIDs(ids...)
	return akc
}

// AddCategories adds the "categories" edges to the Category entity.
func (akc *AccessKeysCreate) AddCategories(c ...*Category) *AccessKeysCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return akc.AddCategoryIDs(ids...)
}

// Mutation returns the AccessKeysMutation object of the builder.
func (akc *AccessKeysCreate) Mutation() *AccessKeysMutation {
	return akc.mutation
}

// Save creates the AccessKeys in the database.
func (akc *AccessKeysCreate) Save(ctx context.Context) (*AccessKeys, error) {
	return withHooks(ctx, akc.sqlSave, akc.mutation, akc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (akc *AccessKeysCreate) SaveX(ctx context.Context) *AccessKeys {
	v, err := akc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (akc *AccessKeysCreate) Exec(ctx context.Context) error {
	_, err := akc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (akc *AccessKeysCreate) ExecX(ctx context.Context) {
	if err := akc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (akc *AccessKeysCreate) check() error {
	if _, ok := akc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "AccessKeys.key"`)}
	}
	if _, ok := akc.mutation.User(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required field "AccessKeys.user"`)}
	}
	return nil
}

func (akc *AccessKeysCreate) sqlSave(ctx context.Context) (*AccessKeys, error) {
	if err := akc.check(); err != nil {
		return nil, err
	}
	_node, _spec := akc.createSpec()
	if err := sqlgraph.CreateNode(ctx, akc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	akc.mutation.id = &_node.ID
	akc.mutation.done = true
	return _node, nil
}

func (akc *AccessKeysCreate) createSpec() (*AccessKeys, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessKeys{config: akc.config}
		_spec = sqlgraph.NewCreateSpec(accesskeys.Table, sqlgraph.NewFieldSpec(accesskeys.FieldID, field.TypeInt))
	)
	if value, ok := akc.mutation.Key(); ok {
		_spec.SetField(accesskeys.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := akc.mutation.User(); ok {
		_spec.SetField(accesskeys.FieldUser, field.TypeString, value)
		_node.User = value
	}
	if nodes := akc.mutation.ProductsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesskeys.ProductsTable,
			Columns: []string{accesskeys.ProductsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := akc.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accesskeys.CategoriesTable,
			Columns: []string{accesskeys.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccessKeysCreateBulk is the builder for creating many AccessKeys entities in bulk.
type AccessKeysCreateBulk struct {
	config
	err      error
	builders []*AccessKeysCreate
}

// Save creates the AccessKeys entities in the database.
func (akcb *AccessKeysCreateBulk) Save(ctx context.Context) ([]*AccessKeys, error) {
	if akcb.err != nil {
		return nil, akcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(akcb.builders))
	nodes := make([]*AccessKeys, len(akcb.builders))
	mutators := make([]Mutator, len(akcb.builders))
	for i := range akcb.builders {
		func(i int, root context.Context) {
			builder := akcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessKeysMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, akcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, akcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, akcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (akcb *AccessKeysCreateBulk) SaveX(ctx context.Context) []*AccessKeys {
	v, err := akcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (akcb *AccessKeysCreateBulk) Exec(ctx context.Context) error {
	_, err := akcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (akcb *AccessKeysCreateBulk) ExecX(ctx context.Context) {
	if err := akcb.Exec(ctx); err != nil {
		panic(err)
	}
}
