// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bd_test/internals/server/ent/accesskeys"
	"bd_test/internals/server/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessKeysDelete is the builder for deleting a AccessKeys entity.
type AccessKeysDelete struct {
	config
	hooks    []Hook
	mutation *AccessKeysMutation
}

// Where appends a list predicates to the AccessKeysDelete builder.
func (akd *AccessKeysDelete) Where(ps ...predicate.AccessKeys) *AccessKeysDelete {
	akd.mutation.Where(ps...)
	return akd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (akd *AccessKeysDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, akd.sqlExec, akd.mutation, akd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (akd *AccessKeysDelete) ExecX(ctx context.Context) int {
	n, err := akd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (akd *AccessKeysDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accesskeys.Table, sqlgraph.NewFieldSpec(accesskeys.FieldID, field.TypeInt))
	if ps := akd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, akd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	akd.mutation.done = true
	return affected, err
}

// AccessKeysDeleteOne is the builder for deleting a single AccessKeys entity.
type AccessKeysDeleteOne struct {
	akd *AccessKeysDelete
}

// Where appends a list predicates to the AccessKeysDelete builder.
func (akdo *AccessKeysDeleteOne) Where(ps ...predicate.AccessKeys) *AccessKeysDeleteOne {
	akdo.akd.mutation.Where(ps...)
	return akdo
}

// Exec executes the deletion query.
func (akdo *AccessKeysDeleteOne) Exec(ctx context.Context) error {
	n, err := akdo.akd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accesskeys.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (akdo *AccessKeysDeleteOne) ExecX(ctx context.Context) {
	if err := akdo.Exec(ctx); err != nil {
		panic(err)
	}
}
