// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bd_test/internals/server/ent/accesskeys"
	"bd_test/internals/server/ent/category"
	"bd_test/internals/server/ent/predicate"
	"bd_test/internals/server/ent/product"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessKeysQuery is the builder for querying AccessKeys entities.
type AccessKeysQuery struct {
	config
	ctx            *QueryContext
	order          []accesskeys.OrderOption
	inters         []Interceptor
	predicates     []predicate.AccessKeys
	withProducts   *ProductQuery
	withCategories *CategoryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AccessKeysQuery builder.
func (akq *AccessKeysQuery) Where(ps ...predicate.AccessKeys) *AccessKeysQuery {
	akq.predicates = append(akq.predicates, ps...)
	return akq
}

// Limit the number of records to be returned by this query.
func (akq *AccessKeysQuery) Limit(limit int) *AccessKeysQuery {
	akq.ctx.Limit = &limit
	return akq
}

// Offset to start from.
func (akq *AccessKeysQuery) Offset(offset int) *AccessKeysQuery {
	akq.ctx.Offset = &offset
	return akq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (akq *AccessKeysQuery) Unique(unique bool) *AccessKeysQuery {
	akq.ctx.Unique = &unique
	return akq
}

// Order specifies how the records should be ordered.
func (akq *AccessKeysQuery) Order(o ...accesskeys.OrderOption) *AccessKeysQuery {
	akq.order = append(akq.order, o...)
	return akq
}

// QueryProducts chains the current query on the "products" edge.
func (akq *AccessKeysQuery) QueryProducts() *ProductQuery {
	query := (&ProductClient{config: akq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := akq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := akq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accesskeys.Table, accesskeys.FieldID, selector),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, accesskeys.ProductsTable, accesskeys.ProductsColumn),
		)
		fromU = sqlgraph.SetNeighbors(akq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCategories chains the current query on the "categories" edge.
func (akq *AccessKeysQuery) QueryCategories() *CategoryQuery {
	query := (&CategoryClient{config: akq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := akq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := akq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accesskeys.Table, accesskeys.FieldID, selector),
			sqlgraph.To(category.Table, category.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, accesskeys.CategoriesTable, accesskeys.CategoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(akq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AccessKeys entity from the query.
// Returns a *NotFoundError when no AccessKeys was found.
func (akq *AccessKeysQuery) First(ctx context.Context) (*AccessKeys, error) {
	nodes, err := akq.Limit(1).All(setContextOp(ctx, akq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{accesskeys.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (akq *AccessKeysQuery) FirstX(ctx context.Context) *AccessKeys {
	node, err := akq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AccessKeys ID from the query.
// Returns a *NotFoundError when no AccessKeys ID was found.
func (akq *AccessKeysQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = akq.Limit(1).IDs(setContextOp(ctx, akq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{accesskeys.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (akq *AccessKeysQuery) FirstIDX(ctx context.Context) int {
	id, err := akq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AccessKeys entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AccessKeys entity is found.
// Returns a *NotFoundError when no AccessKeys entities are found.
func (akq *AccessKeysQuery) Only(ctx context.Context) (*AccessKeys, error) {
	nodes, err := akq.Limit(2).All(setContextOp(ctx, akq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{accesskeys.Label}
	default:
		return nil, &NotSingularError{accesskeys.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (akq *AccessKeysQuery) OnlyX(ctx context.Context) *AccessKeys {
	node, err := akq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AccessKeys ID in the query.
// Returns a *NotSingularError when more than one AccessKeys ID is found.
// Returns a *NotFoundError when no entities are found.
func (akq *AccessKeysQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = akq.Limit(2).IDs(setContextOp(ctx, akq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{accesskeys.Label}
	default:
		err = &NotSingularError{accesskeys.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (akq *AccessKeysQuery) OnlyIDX(ctx context.Context) int {
	id, err := akq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AccessKeysSlice.
func (akq *AccessKeysQuery) All(ctx context.Context) ([]*AccessKeys, error) {
	ctx = setContextOp(ctx, akq.ctx, ent.OpQueryAll)
	if err := akq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AccessKeys, *AccessKeysQuery]()
	return withInterceptors[[]*AccessKeys](ctx, akq, qr, akq.inters)
}

// AllX is like All, but panics if an error occurs.
func (akq *AccessKeysQuery) AllX(ctx context.Context) []*AccessKeys {
	nodes, err := akq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AccessKeys IDs.
func (akq *AccessKeysQuery) IDs(ctx context.Context) (ids []int, err error) {
	if akq.ctx.Unique == nil && akq.path != nil {
		akq.Unique(true)
	}
	ctx = setContextOp(ctx, akq.ctx, ent.OpQueryIDs)
	if err = akq.Select(accesskeys.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (akq *AccessKeysQuery) IDsX(ctx context.Context) []int {
	ids, err := akq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (akq *AccessKeysQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, akq.ctx, ent.OpQueryCount)
	if err := akq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, akq, querierCount[*AccessKeysQuery](), akq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (akq *AccessKeysQuery) CountX(ctx context.Context) int {
	count, err := akq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (akq *AccessKeysQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, akq.ctx, ent.OpQueryExist)
	switch _, err := akq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (akq *AccessKeysQuery) ExistX(ctx context.Context) bool {
	exist, err := akq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AccessKeysQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (akq *AccessKeysQuery) Clone() *AccessKeysQuery {
	if akq == nil {
		return nil
	}
	return &AccessKeysQuery{
		config:         akq.config,
		ctx:            akq.ctx.Clone(),
		order:          append([]accesskeys.OrderOption{}, akq.order...),
		inters:         append([]Interceptor{}, akq.inters...),
		predicates:     append([]predicate.AccessKeys{}, akq.predicates...),
		withProducts:   akq.withProducts.Clone(),
		withCategories: akq.withCategories.Clone(),
		// clone intermediate query.
		sql:  akq.sql.Clone(),
		path: akq.path,
	}
}

// WithProducts tells the query-builder to eager-load the nodes that are connected to
// the "products" edge. The optional arguments are used to configure the query builder of the edge.
func (akq *AccessKeysQuery) WithProducts(opts ...func(*ProductQuery)) *AccessKeysQuery {
	query := (&ProductClient{config: akq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	akq.withProducts = query
	return akq
}

// WithCategories tells the query-builder to eager-load the nodes that are connected to
// the "categories" edge. The optional arguments are used to configure the query builder of the edge.
func (akq *AccessKeysQuery) WithCategories(opts ...func(*CategoryQuery)) *AccessKeysQuery {
	query := (&CategoryClient{config: akq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	akq.withCategories = query
	return akq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AccessKeys.Query().
//		GroupBy(accesskeys.FieldKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (akq *AccessKeysQuery) GroupBy(field string, fields ...string) *AccessKeysGroupBy {
	akq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AccessKeysGroupBy{build: akq}
	grbuild.flds = &akq.ctx.Fields
	grbuild.label = accesskeys.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Key string `json:"key,omitempty"`
//	}
//
//	client.AccessKeys.Query().
//		Select(accesskeys.FieldKey).
//		Scan(ctx, &v)
func (akq *AccessKeysQuery) Select(fields ...string) *AccessKeysSelect {
	akq.ctx.Fields = append(akq.ctx.Fields, fields...)
	sbuild := &AccessKeysSelect{AccessKeysQuery: akq}
	sbuild.label = accesskeys.Label
	sbuild.flds, sbuild.scan = &akq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AccessKeysSelect configured with the given aggregations.
func (akq *AccessKeysQuery) Aggregate(fns ...AggregateFunc) *AccessKeysSelect {
	return akq.Select().Aggregate(fns...)
}

func (akq *AccessKeysQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range akq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, akq); err != nil {
				return err
			}
		}
	}
	for _, f := range akq.ctx.Fields {
		if !accesskeys.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if akq.path != nil {
		prev, err := akq.path(ctx)
		if err != nil {
			return err
		}
		akq.sql = prev
	}
	return nil
}

func (akq *AccessKeysQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AccessKeys, error) {
	var (
		nodes       = []*AccessKeys{}
		_spec       = akq.querySpec()
		loadedTypes = [2]bool{
			akq.withProducts != nil,
			akq.withCategories != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AccessKeys).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AccessKeys{config: akq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, akq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := akq.withProducts; query != nil {
		if err := akq.loadProducts(ctx, query, nodes,
			func(n *AccessKeys) { n.Edges.Products = []*Product{} },
			func(n *AccessKeys, e *Product) { n.Edges.Products = append(n.Edges.Products, e) }); err != nil {
			return nil, err
		}
	}
	if query := akq.withCategories; query != nil {
		if err := akq.loadCategories(ctx, query, nodes,
			func(n *AccessKeys) { n.Edges.Categories = []*Category{} },
			func(n *AccessKeys, e *Category) { n.Edges.Categories = append(n.Edges.Categories, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (akq *AccessKeysQuery) loadProducts(ctx context.Context, query *ProductQuery, nodes []*AccessKeys, init func(*AccessKeys), assign func(*AccessKeys, *Product)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*AccessKeys)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(product.FieldAccessKeyID)
	}
	query.Where(predicate.Product(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(accesskeys.ProductsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AccessKeyID
		if fk == nil {
			return fmt.Errorf(`foreign-key "access_key_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "access_key_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (akq *AccessKeysQuery) loadCategories(ctx context.Context, query *CategoryQuery, nodes []*AccessKeys, init func(*AccessKeys), assign func(*AccessKeys, *Category)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*AccessKeys)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(category.FieldAccessKeyID)
	}
	query.Where(predicate.Category(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(accesskeys.CategoriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AccessKeyID
		if fk == nil {
			return fmt.Errorf(`foreign-key "access_key_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "access_key_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (akq *AccessKeysQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := akq.querySpec()
	_spec.Node.Columns = akq.ctx.Fields
	if len(akq.ctx.Fields) > 0 {
		_spec.Unique = akq.ctx.Unique != nil && *akq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, akq.driver, _spec)
}

func (akq *AccessKeysQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(accesskeys.Table, accesskeys.Columns, sqlgraph.NewFieldSpec(accesskeys.FieldID, field.TypeInt))
	_spec.From = akq.sql
	if unique := akq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if akq.path != nil {
		_spec.Unique = true
	}
	if fields := akq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accesskeys.FieldID)
		for i := range fields {
			if fields[i] != accesskeys.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := akq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := akq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := akq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := akq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (akq *AccessKeysQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(akq.driver.Dialect())
	t1 := builder.Table(accesskeys.Table)
	columns := akq.ctx.Fields
	if len(columns) == 0 {
		columns = accesskeys.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if akq.sql != nil {
		selector = akq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if akq.ctx.Unique != nil && *akq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range akq.predicates {
		p(selector)
	}
	for _, p := range akq.order {
		p(selector)
	}
	if offset := akq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := akq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AccessKeysGroupBy is the group-by builder for AccessKeys entities.
type AccessKeysGroupBy struct {
	selector
	build *AccessKeysQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (akgb *AccessKeysGroupBy) Aggregate(fns ...AggregateFunc) *AccessKeysGroupBy {
	akgb.fns = append(akgb.fns, fns...)
	return akgb
}

// Scan applies the selector query and scans the result into the given value.
func (akgb *AccessKeysGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, akgb.build.ctx, ent.OpQueryGroupBy)
	if err := akgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccessKeysQuery, *AccessKeysGroupBy](ctx, akgb.build, akgb, akgb.build.inters, v)
}

func (akgb *AccessKeysGroupBy) sqlScan(ctx context.Context, root *AccessKeysQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(akgb.fns))
	for _, fn := range akgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*akgb.flds)+len(akgb.fns))
		for _, f := range *akgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*akgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := akgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AccessKeysSelect is the builder for selecting fields of AccessKeys entities.
type AccessKeysSelect struct {
	*AccessKeysQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aks *AccessKeysSelect) Aggregate(fns ...AggregateFunc) *AccessKeysSelect {
	aks.fns = append(aks.fns, fns...)
	return aks
}

// Scan applies the selector query and scans the result into the given value.
func (aks *AccessKeysSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aks.ctx, ent.OpQuerySelect)
	if err := aks.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccessKeysQuery, *AccessKeysSelect](ctx, aks.AccessKeysQuery, aks, aks.inters, v)
}

func (aks *AccessKeysSelect) sqlScan(ctx context.Context, root *AccessKeysQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aks.fns))
	for _, fn := range aks.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aks.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
