// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bd_test/internals/server/ent/accesskeys"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AccessKeys is the model entity for the AccessKeys schema.
type AccessKeys struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// User holds the value of the "user" field.
	User string `json:"user,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccessKeysQuery when eager-loading is set.
	Edges        AccessKeysEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccessKeysEdges holds the relations/edges for other nodes in the graph.
type AccessKeysEdges struct {
	// Products holds the value of the products edge.
	Products []*Product `json:"products,omitempty"`
	// Categories holds the value of the categories edge.
	Categories []*Category `json:"categories,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProductsOrErr returns the Products value or an error if the edge
// was not loaded in eager-loading.
func (e AccessKeysEdges) ProductsOrErr() ([]*Product, error) {
	if e.loadedTypes[0] {
		return e.Products, nil
	}
	return nil, &NotLoadedError{edge: "products"}
}

// CategoriesOrErr returns the Categories value or an error if the edge
// was not loaded in eager-loading.
func (e AccessKeysEdges) CategoriesOrErr() ([]*Category, error) {
	if e.loadedTypes[1] {
		return e.Categories, nil
	}
	return nil, &NotLoadedError{edge: "categories"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccessKeys) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accesskeys.FieldID:
			values[i] = new(sql.NullInt64)
		case accesskeys.FieldKey, accesskeys.FieldUser:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccessKeys fields.
func (ak *AccessKeys) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accesskeys.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ak.ID = int(value.Int64)
		case accesskeys.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				ak.Key = value.String
			}
		case accesskeys.FieldUser:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user", values[i])
			} else if value.Valid {
				ak.User = value.String
			}
		default:
			ak.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccessKeys.
// This includes values selected through modifiers, order, etc.
func (ak *AccessKeys) Value(name string) (ent.Value, error) {
	return ak.selectValues.Get(name)
}

// QueryProducts queries the "products" edge of the AccessKeys entity.
func (ak *AccessKeys) QueryProducts() *ProductQuery {
	return NewAccessKeysClient(ak.config).QueryProducts(ak)
}

// QueryCategories queries the "categories" edge of the AccessKeys entity.
func (ak *AccessKeys) QueryCategories() *CategoryQuery {
	return NewAccessKeysClient(ak.config).QueryCategories(ak)
}

// Update returns a builder for updating this AccessKeys.
// Note that you need to call AccessKeys.Unwrap() before calling this method if this AccessKeys
// was returned from a transaction, and the transaction was committed or rolled back.
func (ak *AccessKeys) Update() *AccessKeysUpdateOne {
	return NewAccessKeysClient(ak.config).UpdateOne(ak)
}

// Unwrap unwraps the AccessKeys entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ak *AccessKeys) Unwrap() *AccessKeys {
	_tx, ok := ak.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccessKeys is not a transactional entity")
	}
	ak.config.driver = _tx.drv
	return ak
}

// String implements the fmt.Stringer.
func (ak *AccessKeys) String() string {
	var builder strings.Builder
	builder.WriteString("AccessKeys(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ak.ID))
	builder.WriteString("key=")
	builder.WriteString(ak.Key)
	builder.WriteString(", ")
	builder.WriteString("user=")
	builder.WriteString(ak.User)
	builder.WriteByte(')')
	return builder.String()
}

// AccessKeysSlice is a parsable slice of AccessKeys.
type AccessKeysSlice []*AccessKeys
