// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccessKeys is the predicate function for accesskeys builders.
type AccessKeys func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)
