// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccessKeysColumns holds the columns for the "access_keys" table.
	AccessKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "user", Type: field.TypeString, Unique: true},
	}
	// AccessKeysTable holds the schema information for the "access_keys" table.
	AccessKeysTable = &schema.Table{
		Name:       "access_keys",
		Columns:    AccessKeysColumns,
		PrimaryKey: []*schema.Column{AccessKeysColumns[0]},
	}
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "access_key_id", Type: field.TypeInt, Nullable: true},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "categories_access_keys_categories",
				Columns:    []*schema.Column{CategoriesColumns[2]},
				RefColumns: []*schema.Column{AccessKeysColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "description", Type: field.TypeString},
		{Name: "image_url", Type: field.TypeString},
		{Name: "access_key_id", Type: field.TypeInt, Nullable: true},
		{Name: "category_id", Type: field.TypeInt, Nullable: true},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "products_access_keys_products",
				Columns:    []*schema.Column{ProductsColumns[5]},
				RefColumns: []*schema.Column{AccessKeysColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "products_categories_products",
				Columns:    []*schema.Column{ProductsColumns[6]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccessKeysTable,
		CategoriesTable,
		ProductsTable,
	}
)

func init() {
	CategoriesTable.ForeignKeys[0].RefTable = AccessKeysTable
	ProductsTable.ForeignKeys[0].RefTable = AccessKeysTable
	ProductsTable.ForeignKeys[1].RefTable = CategoriesTable
}
